### ISSUE TITLE
Building Issue

### ISSUE THREAD

**Issue by HenryDane** [artillect/Voltaics#10]
So I was trying to build this (second time?) and I get this error:
`C:\Users\*******\.gradle\caches\minecraft\net\minecraftforge\forge\1.12.2-14.23.3.2698\userdev\dev.json could not be parsed`.
What is going on?

I am simply executing 
`gradlew setupDecomWorkspace`.

More of the error:
```
* What went wrong:
A problem occurred configuring root project 'Voltaics'.
> java.io.FileNotFoundException: Inherited json file (1.12.2) not found! Maybe you are running in offline mode?
```

**Comment by HenryDane** [comment]
Executing with `--stacktrace` yeilds:
```
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring root project 'Voltaics'.
 . . . 
```

**Comment by HenryDane** [comment]
So according to [this forum post](url), 

>  It turns out that, as of build 1583, Forge requires ForgeGradle 2.1 - but that hasn't been released yet, so you have to set up build.gradle to use the latest snapshot of ForgeGradle.

So I am gonna make the changes and recommit them so that this hopefully won't be an issue.

**Comment by artillect** [comment]
I had it build fine without forgegradle 2.1. If it works with your changes then by all means submit a PR.

**Comment by HenryDane** [comment]
So after a few hours I still do not know what is wrong. The interwebs have very little to say about this. I am gonna give up.

**Comment by dmarcuse** [comment]
Try clearing the gradle caches (just delete the `.gradle/caches` directory mentioned earlier) and see if that helps. Try a clean re-clone as well, just to be safe.

**Comment by HenryDane** [comment]
Well I changed line 24 of build.gradle to `version = "1.12.2-14.23.3.2655"` from `version = "1.12.2-14.23.3.2698"` and I guess that that fixed it. 

Not my first ugly hack.

**Comment by artillect** [comment]
You can't just change the forge version you're building on, solve this pls.

**Comment by HenryDane** [comment]
Ok so current status, cleaning all caches and recloning. Current error is 
```
java.lang.Error: Unresolved compilation problem: 
	IForgeRegistry cannot be resolved to a type
```

**Comment by artillect** [comment]
Resolved in the discord
