### ISSUE TITLE
Registry

### ISSUE THREAD

**Issue by HenryDane** [artillect/Voltaics#11]
Evidently according to [](url):

> The registry system has been overhauled in 1.12, you need to use registry events. Forge's documentation explains them here. You can see some examples in my mod's init classes. 

This means that things like 
```
GameRegistry.register(this);
```
do not work in 1.12 and we need to switch to registry events, whatever those are.

**Comment by artillect** [comment]
I'll fix this

**Comment by artillect** [comment]
Solved in https://github.com/artillect/Voltaics/commit/fa3cfb2d970fcd4c1db69aac8bd64ce573380697
